// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Machine = require("./Machine.bs.js");

function createCounterMachine(param) {
  return Machine.createMachine({
              TAG: /* Idle */0,
              _0: 0
            }, (function (state, $$event, param) {
                if (state.TAG !== /* Idle */0) {
                  if ($$event >= 4) {
                    return {
                            TAG: /* Idle */0,
                            _0: state._0
                          };
                  } else {
                    return state;
                  }
                }
                var value = state._0;
                switch ($$event) {
                  case /* Increment */0 :
                      return {
                              TAG: /* Idle */0,
                              _0: value + 1 | 0
                            };
                  case /* Decrement */1 :
                      return {
                              TAG: /* Idle */0,
                              _0: value - 1 | 0
                            };
                  case /* Reset */2 :
                      return {
                              TAG: /* Idle */0,
                              _0: 0
                            };
                  case /* Pause */3 :
                      return {
                              TAG: /* Paused */1,
                              _0: value
                            };
                  case /* Unpause */4 :
                      return state;
                  
                }
              }));
}

exports.createCounterMachine = createCounterMachine;
/* No side effect */
