// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function createSubject(initial) {
  var value = {
    contents: initial
  };
  var nextId = {
    contents: 0
  };
  var listeners = [];
  return {
          listen: (function (listener) {
              var id = nextId.contents;
              nextId.contents = id + 1 | 0;
              listeners.push({
                    id: id,
                    listener: listener
                  });
              Curry._1(listener, value.contents);
              return function (param) {
                var index = listeners.reduce((function (foundIndex, listener, index) {
                        if (listener.id === id) {
                          return index;
                        } else {
                          return foundIndex;
                        }
                      }), -1);
                if (index >= 0) {
                  listeners.splice(index);
                  return ;
                }
                
              };
            }),
          get: (function (param) {
              return value.contents;
            }),
          set: (function (v) {
              value.contents = v;
              listeners.forEach(function (param) {
                    return Curry._1(param.listener, v);
                  });
              
            })
        };
}

exports.createSubject = createSubject;
/* No side effect */
